version: '2.2'
services:
  app:
    container_name: sbqueue
    build: .
    ports:
      - "8080:8080"
    depends_on:
      elasticmq:
        condition: service_started
      postgres:
        condition: service_healthy

  elasticmq:
    container_name: elasticmq
    image: s12v/elasticmq
    ports:
      - "9324:9324"

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "storage"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d storage"]
      interval: 10s
      timeout: 10s
      retries: 1