version: '2.2'
services:
  config-api:
    container_name: spring-boot-queue-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      config-elasticmq:
        condition: service_started
  config-elasticmq:
    container_name: elasticmq
    image: s12v/elasticmq
    ports:
      - "9324:9324"
  config-postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=storage